# Generated by Django 5.0.6 on 2024-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_personalspace_created_at_personalspace_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalspace',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
