# Generated by Django 5.0.6 on 2024-06-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_task_end_date_remove_task_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_contractor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
    ]
