# Generated by Django 5.0.6 on 2024-06-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_is_contractor_remove_user_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
    ]
